import * as T from 'three';
import {ease} from './simulation.js';
export function createExplorer({parts,camera,controls,canvas,sim,onClear,getCameraMode=()=> 'SYSTEM',restoreCameraMode=()=>{}}){
 let state='EXPLODED',part=null,saved=null,transition=null,pending=null,drag=null,hover=null,fadeAmount=0;
 const card=document.getElementById('part-card');
 card.innerHTML='<button id="return-part">← 返回爆炸圖</button><small>PART EXPLORER · 360°</small><h3 id="detail-title"></h3><p id="detail-name-en"></p><p id="detail-id"></p><p id="detail-function"></p><details id="detail-more"><summary>了解更多</summary><p id="detail-category"></p><p id="detail-material"></p><p id="detail-function-en"></p><p id="detail-layer"></p></details><div class="detail-views"><button data-detail="front">正面</button><button data-detail="back">背面</button><button data-detail="side">側面</button></div><small class="detail-gesture">拖曳旋轉零件 · 滾輪縮放</small>';
 const picker=document.createElement('details');picker.id='part-picker';picker.hidden=true;picker.innerHTML='<summary>探索零件 · '+parts.length+' COMPONENTS</summary><div></div>';document.querySelector('.controls').prepend(picker);
 for(const category of ['CASE','DISPLAY','CALENDAR','BRIDGES','GEAR TRAIN','ESCAPEMENT','BALANCE','POWER','CONTROL']){
  const section=document.createElement('section'),heading=document.createElement('h4');heading.textContent=category;section.append(heading);
  for(const p of parts.filter(p=>p.userData.explorer_category===category)){const b=document.createElement('button');b.textContent=p.name+' · '+p.userData.name_zh;b.dataset.part=p.name;b.onclick=()=>{picker.open=false;enter(p);};section.append(b);}picker.lastElementChild.append(section);
 }
 const originals=new Map();parts.forEach(p=>p.traverse(m=>{if(m.isMesh)originals.set(m,{opacity:m.material.opacity,transparent:m.material.transparent,depthWrite:m.material.depthWrite});}));
 function fade(t){fadeAmount=t;for(const p of parts)if(p!==part)p.traverse(m=>{if(m.isMesh){const o=originals.get(m);const transparent=t>0||o.transparent;if(m.material.transparent!==transparent){m.material.transparent=transparent;m.material.needsUpdate=true;}m.visible=t<.999;m.material.opacity=o.opacity*(1-t);m.material.depthWrite=t>0?false:o.depthWrite;}});}
 function clearHover(){if(hover)hover.traverse(m=>{if(m.isMesh)m.material.emissive.set(0);});hover=null;}
 function enter(p){if(part||sim.time!==9||sim.auto)return;clearHover();onClear();part=p;part.traverse(m=>{if(m.isMesh)m.material.emissive.set(0x4a3510);});state='PART_SELECTED';saved={position:p.position.clone(),quaternion:p.quaternion.clone(),camera:camera.position.clone(),target:controls.target.clone(),cameraQuaternion:camera.quaternion.clone(),zoom:camera.zoom,fov:camera.fov,mode:getCameraMode(),paused:sim.paused,min:controls.minDistance,max:controls.maxDistance,rotate:controls.autoRotate,viewX:camera.view?.offsetX||0,viewY:camera.view?.offsetY||0,scrollY:typeof window!=='undefined'?window.scrollY:0};sim.paused=true;controls.autoRotate=false;controls.minDistance=.15;controls.maxDistance=40;
  const box=new T.Box3().setFromObject(p),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3()).sub(p.position),target=new T.Vector3(0,0,1),position=target.clone().sub(center),radius=Math.max(size.length()*1.8,.9);
  transition={t:0,from:p.position.clone(),to:position,cameraFrom:camera.position.clone(),cameraTo:target.clone().add(new T.Vector3(.35,-.4,1).normalize().multiplyScalar(radius)),targetFrom:controls.target.clone(),targetTo:target};
  const d=p.userData;document.getElementById('detail-title').textContent=d.name_zh;document.getElementById('detail-name-en').textContent=d.name_en;document.getElementById('detail-id').textContent=d.part_id+' · '+d.category_zh;document.getElementById('detail-layer').textContent='ASSEMBLY LAYER '+d.assembly_layer;document.getElementById('detail-more').open=false;document.getElementById('detail-category').textContent=d.category_zh+' / '+d.category_en;document.getElementById('detail-material').textContent=d.material;document.getElementById('detail-function').textContent=d.function_zh;document.getElementById('detail-function-en').textContent=d.function_en;card.hidden=false;document.body.classList.add('part-detail');if(typeof window!=='undefined'&&innerWidth<=760)window.scrollTo(0,0);picker.hidden=true;
 }
 function leave(callback=null){if(!part){callback?.();return;}if(callback)pending=callback;if(state==='PART_RETURNING')return;state='PART_RETURNING';drag=null;transition={t:0,from:part.position.clone(),to:saved.position,cameraFrom:camera.position.clone(),cameraTo:saved.camera,targetFrom:controls.target.clone(),targetTo:saved.target,quaternion:part.quaternion.clone(),fadeStart:fadeAmount,viewX:camera.view?.offsetX||0};}
 document.getElementById('return-part').onclick=()=>leave();
 card.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{if(state!=='PART_DETAIL')return;const d={front:[0,0,1],back:[0,0,-1],side:[1,0,.02]}[b.dataset.detail];transition={t:0,from:part.position.clone(),to:part.position.clone(),cameraFrom:camera.position.clone(),cameraTo:controls.target.clone().addScaledVector(new T.Vector3(...d).normalize(),camera.position.distanceTo(controls.target)),targetFrom:controls.target.clone(),targetTo:controls.target.clone(),viewOnly:true};});
 const ray=new T.Raycaster(),pointer=new T.Vector2();
 function hit(e){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);let h=ray.intersectObjects(parts,true)[0]?.object;while(h&&h.parent!==parts[0].parent)h=h.parent;return h;}
 canvas.addEventListener('pointermove',e=>{if(part){if(drag&&drag.id===e.pointerId&&state==='PART_DETAIL'&&!transition){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;const qx=new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0).applyQuaternion(camera.quaternion),dx*.008),qy=new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0).applyQuaternion(camera.quaternion),dy*.008);part.quaternion.premultiply(qx).premultiply(qy);drag.x=e.clientX;drag.y=e.clientY;}return;}if(e.pointerType==='mouse'&&sim.time===9&&!sim.auto){const p=hit(e);if(p!==hover){clearHover();hover=p;if(p)p.traverse(m=>{if(m.isMesh)m.material.emissive.set(0x4a3510);});canvas.style.cursor=p?'pointer':'grab';}}});
 // OrbitControls remains responsible for two-finger dolly; one-finger rotate acts on the assembly.
 const touches=new Set();canvas.addEventListener('pointerdown',e=>{touches.add(e.pointerId);if(state==='PART_DETAIL'&&touches.size===1)drag={id:e.pointerId,x:e.clientX,y:e.clientY};else drag=null;});
 canvas.addEventListener('pointerup',e=>touches.delete(e.pointerId));canvas.addEventListener('pointercancel',e=>touches.delete(e.pointerId));
 canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
 return {enter,leave,get active(){return !!part;},get selected(){return part;},get state(){return part?state:null;},frame(dt){picker.hidden=!!part||sim.time!==9||sim.auto;controls.enableRotate=!part;if(!part)return;controls.autoRotate=false;if(transition){const a=transition;a.t+=dt;const t=ease(a.t/1.5);part.position.lerpVectors(a.from,a.to,t);camera.position.lerpVectors(a.cameraFrom,a.cameraTo,t);controls.target.lerpVectors(a.targetFrom,a.targetTo,t);if(!a.viewOnly){const w=canvas.clientWidth,h=canvas.clientHeight,from=state==='PART_RETURNING'?a.viewX:saved.viewX,to=state==='PART_RETURNING'?saved.viewX:(innerWidth<=760?0:w*.08);camera.setViewOffset(w,h,from+(to-from)*t,saved.viewY,w,h);if(state==='PART_RETURNING'){part.quaternion.slerpQuaternions(a.quaternion,saved.quaternion,t);fade(a.fadeStart*(1-t));}else fade(t);}if(t>=1){transition=null;if(state==='PART_RETURNING'){part.position.copy(saved.position);part.quaternion.copy(saved.quaternion);camera.position.copy(saved.camera);camera.quaternion.copy(saved.cameraQuaternion);camera.zoom=saved.zoom;camera.fov=saved.fov;camera.updateProjectionMatrix();controls.target.copy(saved.target);restoreCameraMode(saved.mode);controls.minDistance=saved.min;controls.maxDistance=saved.max;sim.paused=saved.paused;controls.autoRotate=saved.rotate;fade(0);part.traverse(m=>{if(m.isMesh)m.material.emissive.set(0);});part=null;const oldScroll=saved.scrollY;saved=null;card.hidden=true;document.body.classList.remove('part-detail');if(typeof window!=='undefined'&&innerWidth<=760)window.scrollTo(0,oldScroll);state='EXPLODED';controls.enableRotate=true;const cb=pending;pending=null;cb?.();}else {state='PART_DETAIL';part.traverse(m=>{if(m.isMesh)m.material.emissive.set(0);});}}}},snapshot(){return {state,selected:part?.name||null,selectedQuaternion:part?.quaternion.toArray()||null,savedCamera:saved?{position:saved.camera.toArray(),quaternion:saved.cameraQuaternion.toArray(),target:saved.target.toArray(),distance:saved.camera.distanceTo(saved.target),zoom:saved.zoom,fov:saved.fov,mode:saved.mode}:null};}};
}
